version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - cai-net

  # Python library is here
  cai_py:
    build:
      context: .
      dockerfile: Dockerfile_python
    container_name: cai_py
    depends_on:
      - redis
      - chromadb
    ports:
      - "4041:4041"
    command: ["python", "main.py"]
    networks:
      - cai-net
    restart: always

  cai_go:
    build:
      context: .
      dockerfile: Dockerfile_go
    container_name: cai_go
    restart: always
    depends_on:
      - redis
      - cai_py
    ports:
      - "4400:4400"
    command: ["/app/main"]
    networks:
      - cai-net

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - "8000:8000"
    networks:
      - cai-net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  cai-net:
    name: cai-net
    driver: bridge
