# Stage 1: Build dependencies using conda installer
FROM continuumio/miniconda3:latest as builder
# Create a Conda environment and install packages
WORKDIR /app


# Copy only the requirements file to ensure caching
COPY requirements.txt /tmp/requirements.txt
COPY environment.yml /tmp/environment.yml

#  Copy the app.env
COPY .env .

RUN conda env create -f /tmp/environment.yml

# Activate the Conda environment and set the PATH
SHELL ["conda", "run", "-n", "pyenv", "/bin/bash", "-c"]
ENV PATH /opt/conda/envs/pyenv/bin:$PATH


# Stage 2: Create the final image
FROM python:3.8-slim

# Copy installed dependencies from the builder stage
COPY --from=builder /app /app

# Set the working directory
WORKDIR /app

# Copy the Python script from the internal folder
COPY internal/py/* /app/

# Expose the port if needed
EXPOSE 4041

# Define the command to run your Python application
CMD ["python", "main.py"]