# We initialize Golang first and use the alpine version
# We set the working directory to /app and copy all files inside
# We build the binary and name it main
FROM golang:1.19-alpine3.16 AS builder

WORKDIR /app
# Copy all files from the current directory to the working directory
# including the go.mod and go.sum files
COPY . .
# We build the binary from the backend folder
RUN go build -o main main.go

FROM alpine:3.16
WORKDIR /app
COPY --from=builder /app/main .
COPY .env .


EXPOSE 4400
CMD ["/app/main"]


