# Stage 1: Build dependencies

FROM python:3.8-slim-bookworm as builder
LABEL maintainer="Brian Mwangi"
WORKDIR /app

# Copy only the requirements file to ensure caching
COPY py/requirements.txt .

#  Copy the app.env
COPY .env .

# Install Tesseract and other dependencies
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    && rm -rf /var/lib/apt/lists/*

# Install the dependencies from requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Stage 2: Create the final image
FROM python:3.8-slim-bookworm

# Copy installed dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.8/site-packages /usr/local/lib/python3.8/site-packages
COPY --from=builder /app /app

# Set the working directory
WORKDIR /app

# Copy the Python script from the internal folder
COPY py/src /app/
COPY py/* /app/

# Expose the port if needed
EXPOSE 4041

# Define the command to run your Python application
CMD ["python", "main.py"]