# I am required to run a successful build for
# the conda environment to be created and to set up for ffmpeg
# all of this just to handle audio files from ogg to mp3 :(
name: pyenv

channels:
  - conda-forge

dependencies:
  - python=3.8
  - ffmpeg
  - pip:
    - -r requirements.txt