# Use the official Golang image as a parent image.
FROM golang:1.19-alpine

# Set the Current Working Directory to root.
WORKDIR /

# Copy go mod and sum files to the workspace.
COPY go.mod ../go.sum ./

# Set the Current Working Directory back to /app.
WORKDIR /app

# Download all dependencies.
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container.
COPY . .

# Build the Go app.
RUN go build -o main .

# Expose port 8080 to the outside world.
EXPOSE 8080

# Command to run the executable.
CMD ["./main"]
