version: '3'
services:
  your-service:
    build:
      context: ../  
      dockerfile: docker/Dockerfile  

  go-service:
    build:
      context: ../core-system/server  
      dockerfile: ../../docker/Dockerfile-go  
    ports:
      - "8080:8080"
    networks:
      - mynet
    environment:
      - GO_ENV_VARIABLE=some_value
    volumes:
      - go-data:/path/in/container

  python-service:
    build:
      context: ../  # Assuming this is the root of your project where `ml-microservices` directory is located
      dockerfile: docker/Dockerfile-python  # Adjust this to the relative path of your Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynet
    environment:
      - PYTHON_ENV_VARIABLE=some_value
    volumes:
      - python-data:/path/in/container

  react-service:
    platform: linux
    build:
      context: .  
    volumes:
      - ./src:/app  
      - /app/node_modules
    environment:
      REACT_APP_ENV: "development"

networks:
  mynet:
    driver: bridge

volumes:
  go-data:
  python-data:
  react-src:
  react-node-modules:
