# Dockerfile-python
FROM python:3.8-slim

# Set the Current Working Directory inside the container to root.
WORKDIR /

# Copy requirements.txt
COPY docker/requirements.txt ./

# Install dependencies
RUN pip install -r requirements.txt

# Copy script
COPY ./ml-microservices/processing.py /app/

# Set work directory
WORKDIR /app/ml-microservices

# Set work directory
WORKDIR /app

# Command to run the script
CMD ["python", "processing.py"]
