apiVersion: apps/v1
kind: Deployment
metadata:
  name: cai-api-deployment
  labels:
    app: cai-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cai-api
  template:
    metadata:
      labels:
        app: cai-api
    spec:
      containers:
      - name: cai-ai-go
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:699c5164be7304bded4bb9d54929caef9100a908-go
        ports:
        - containerPort: 4400
      - name: cai-ai-py
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:699c5164be7304bded4bb9d54929caef9100a908-py
        ports:
        - containerPort: 4041