apiVersion: apps/v1
kind: Deployment
metadata:
  name: cai-api-deployment
  labels:
    app: cai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cai-api
  template:
    metadata:
      labels:
        app: cai-api
    spec:
      containers:
      - name: cai-ai-go
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:latest-go
        ports:
        - containerPort: 4400
          name: go-http-server
      - name: cai-ai-py
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:latest-py
        ports:
        - containerPort: 4041
          name: py-http-server