apiVersion: apps/v1
kind: Deployment
metadata:
  name: cai-api-deployment
  labels:
    app: cai-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cai-api
  template:
    metadata:
      labels:
        app: cai-api
    spec:
      containers:
      - name: cai-ai-go
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:133f321ae7ffa3a9326d1bf43d7bf5e4f38cfb86-go
        ports:
        - containerPort: 4400
      - name: cai-ai-py
        imagePullPolicy: Always
        image: 657407981560.dkr.ecr.us-east-2.amazonaws.com/cai:133f321ae7ffa3a9326d1bf43d7bf5e4f38cfb86-py
        ports:
        - containerPort: 4041